### PR TITLE
object_store backend: make d_open actually test for failure

### PR DESCRIPTION
**Pull request by nathanejohnson**
Do a dpl_list_all_my_buckets now to make sure that we can
connect to the storage backend.  Not doing this causes corruption
of backups, it will mark them as successful even if it fails.

### CODE REVIEW

**Comment by mvwieringen** [comment]
Some remarks:

- Indention seems wrong in some places e.g. BAREOS standard is 3 spaces I see some 6 space etc.
- Please leave the goto construction now the function is small (it used to be longer when initialize()
  method was not there but it might get more complex and then the single exit from function is handy.
- Comments should be /* */ and not // again BAREOS standard coding guidelines
- The Dmsg are nice for debugging but I wonder if they make sense to include.

The fact that the backup thinks things succeeded is probably mostly when using the iothreads
as then the storing is decoupled from the backup writing. When using iothreads the upload gets
retried until it succeeds or until the storage daemon is stopped which ever is first. Your patch fixes
the mis-configure case for the backend but if there are intermediate problems like temporary
connection problems the retry logic will still work. There are ways of working around this known
design hole like using local temporary storage and marking things as "inflight" so on restart of
the storage daemon you could start sending stuff that was "inflight" from the last run but that was
out of scope for the customer using this feature which also uses an storage not in the public cloud.

If you can address the above remarks I can merge it into the branch and I think it will then
automatically update the pull request.

Thanks for testing things and suggest enhancements.

I think you can just update your branch and rebase things using the interactive rebase with fixup for
the second commit which will update the original commit and in turn will update the pull request if
I'm not mistaken.

**Comment by nathanejohnson** [comment]
@mvwieringen thank you for looking at this.  I apologize for the whitespace goofs, I believe I should have that sorted now.  I also took out some of the extraneous debug messages and put the goto back.

I believe there might be some other potential pitfalls, I did notice that whenever it would do a flush chunk, it would actually error out in the logs but ultimately it seemed to record files backed up in the catalog that never made it to storage.  We noticed this when we had a misconfiguration of our rados gateway.  I will try to come up with an easy test case and possible another commit to address it.

**Comment by mvwieringen** [comment]
No problem looking at things if they make sense. I guess you tested that you actually can give an
NULL argument to the new call you are making. I have two small nits left. The error message for the
default case of the switch talks about dpl_open I think it better to tell its the dpl_list_all_my_buckets()
is failing. And the comment of setting the errno is still c++ comment and I would just loose it.

As to your other remarks. Yes its a known and calculated design decision that you might get backup
succeeded even when backup never hits the backing store. That is the penalty for the async
despooling and honestly its a calculated risk, first of all I would see this cloud storage as "secondary"
storage e.g. primary on site and copy to secondary cloud storage. The despooling is retried until it
succeeds so intermediate errors should be recoverable also when you do a storage status you will
see pending uploads so when stopping the SD you should make sure there are no pending uploads
anymore.

For now this is way more then existed for a long time and is good enough for now.  If you come up
with a small not to interfering solution we might try it but I myself have no need to make this bullet
proof as it will become pretty hard to maintain and there are a zillion other places things will or can
go wrong.

**Comment by nathanejohnson** [comment]
@mvwieringen I have verified that passing a NULL to this call, it throws away the results of the call, at least for the S3 backend.  Unfortunately this seems to only be implemented for S3, so maybe another call would be appropriate.  For us we'll only ever use S3.

https://github.com/bareos/Droplet/blob/bareos-master/libdroplet/src/backend/s3/backend/list_all_my_buckets.c#L154

vecp here is ultimately what is passed a NULL above, and vec is the internal buffer they used for the response from the rest call.  So if you pass a valid pointer pointer, they assign it for you, otherwise they free the result.

So to that end, can you think of another call that will actually validate that our connection is valid that would at least work with swift?  Here are the low level calls that are implemented in libdroplet:

```c
dpl_backend_swift = 
  {
    "swift",
    .login              = dpl_swift_login,
    .put                = dpl_swift_put,
    .get                = dpl_swift_get,
    .head               = dpl_swift_head,
    .deletef            = dpl_swift_delete
  };
```

**Comment by nathanejohnson** [comment]
Also, as to your earlier post regarding retries, this does not seem to be what we observed.  Again, I'll try to come up with a simple concrete test case.

**Comment by mvwieringen** [comment]
Using a dpl_chdir() to the right bucket is probably a more portable option e.g. that is also used by
the walk_dpl_directory() function which is used for determining the current volume size and for the
truncate. As to the rety logic that only happens when using io-threads as then on error it will put things
back onto the ordered ciricular buffer between the threads. I know for sure that used to work as I once forgot to start my scality docker container with the s3server and after starting it the data did get stored
on the S3 storage after starting it (but not stopping the BAREOS SD).

I would favor if things work for all backend droplet supports as the original idea to use this library
was because of its different backends. Since then Scality seems to have abandoned development
however which is a pity.

**Comment by nathanejohnson** [comment]
@mvwieringen as an update, dpl_chdir(m_ctx, "/") always returns DPL_SUCCESS for S3 at least, so I'm guessing it doesn't actually reach out to the endpoint.  I'll keep playing with it.

**Comment by mvwieringen** [comment]
@nathanejohnson I pushed some extra changes to the branch for the specfile and a config example
and an extra fix for gfapi-fd which was missing a parse for the basedir argument.
Regarding your comment about dpl_chdir() I guess that only sets the current dir in the droplet context
you probably need to do an dpl_opendir() to actually access the storage backend.

**Comment by mvwieringen** [comment]
@nathanejohnson You probably want to rebase your changes on top of the rebased branch as now the pullo request seems to have lost the fact that I rebased mine on top of the current 16.2 tip from upstream.

**Pull request closed without merging**
